### PR TITLE
Add iterative refinement function

### PR DESCRIPTION
**Pull request by MaxenceGollier**
I added a Julia function that given an approximate solution $$x$$ refines a solution of the system $$R^TR x \approx z$$.
Let me know what you think @dpo @amontoison when you have some time.

### CODE REVIEW

**Review by amontoison — CHANGES_REQUESTED** [review]
Can you add entries for `qrm_refine!` and `qrm_refine` in the documentation?

For the docstring of `qrm_refine!`, I suggest to also specify the length of each vector.
You say at the top of the docstring that `(m, n)` is the size of `A` and explain that each vector is of size `n` or `m`.

Good job!

**Comment by dpo** [comment]
@MaxenceGollier thank you. Because `qrm_refine` is so closely tied to the seminormal equations, it would make sense to add functions specifically to solve those equations. They would call `qrm_refine`.

**Comment by MaxenceGollier** [comment]
>You say at the top of the docstring that `(m, n)` is the size of `A` and explain that each vector is of size `n` or `m`.

I prefer to avoid specifying the dimension of `A`. The dimensions of the inputs should depend on the dimension of `R` instead, if  the user calls `qrm_factorize!` with `transp = 't'`, then it is the dimension of `R` that is relevant because we will still solve $$R^TRx = z$$ but for the problem $$AA^T x = z$$ instead of $$A^TAx = z$$ in that case.

> @MaxenceGollier thank you. Because `qrm_refine` is so closely tied to the seminormal equations, it would make sense to add functions specifically to solve those equations. They would call `qrm_refine`.

I agree, I will add a separate PR for that. 
In all cases, thank you for your quick feedback @amontoison, @dpo !

**Review by dpo — APPROVED** [review]

**Comment by MaxenceGollier** [comment]
> Could you add an option to refine `RR'x = b` or `R'Ry = c`? I agree to keep the PR small and focused.
> 
> It will require more work to address the request of Dominique: [#88 (comment)](https://github.com/JuliaSmoothOptimizers/QRMumps.jl/issues/88#issuecomment-2081786094)

I don't see in what situation a problem like `RR' x = b` would arise. Whether the problem is `A' A x = b` or `AA' x = b`, we would still get `R'R x = b`

**Comment by amontoison** [comment]
You're right, except if `A` is square we don't need it because `qr_mumps` requires the QR of `A'` is `A` has more columns than rows.
It's a too specific corner case to spend time on it.

**Review by amontoison — APPROVED** [review]

**Pull request merged**
