### PR TITLE
Interface new routines

### LINKED ISSUE #72: Retrieve the factors?
Is it possible to retrieve the L factor of a positive-definite matrix? Or the R factor of a QR?

### PR DESCRIPTION
**Pull request by amontoison**
close #72 
@abuttari 
I have some errors with the new routines `qrm_spfct_get_rp`, `qrm_spfct_get_cp` and `qrm_spfct_get_r`,
```julia
using QRMumps, SparseArrays

T = Float64
A = sprand(T, 100, 100, 0.05)
spmat = qrm_spmat_init(A)
spfct = qrm_spfct_init(spmat)

qrm_analyse!(spmat, spfct)
qrm_factorize!(spmat, spfct)

rp = qrm_spfct_get_rp(spfct)
cp = qrm_spfct_get_cp(spfct)
R = qrm_spfct_get_r(spfct)
```
```julia
julia> rp = qrm_spfct_get_rp(spfct)
ERROR: Unknown qr_mumps error: 35379072
Stacktrace:
 [1] qrm_spfct_get_rp(spfct::qrm_spfct{Float64})
   @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:9
 [2] top-level scope
   @ REPL[8]:1

julia> cp = qrm_spfct_get_cp(spfct)
ERROR: Unknown qr_mumps error: 29802400
Stacktrace:
 [1] qrm_spfct_get_cp(spfct::qrm_spfct{Float64})
   @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:23
 [2] top-level scope
   @ REPL[9]:1

julia> R = qrm_spfct_get_r(spfct)
100×100 SparseMatrixCSC{Float64, Int32} with 3431 stored entries:
⠀⠄⣾⡆⠀⠈⠀⠀⠁⠀⡎⠀⠠⠤⠤⠈⠅⠀⠸⠈⢵⠀⢼⠰⠨⠀⠀⠤⠆⠥⠀⢰⠀⢴⡦⠄⢴⢶⠠⠀⠀⠠⢼⠀⠨⠩⠇⠅⠀⢼
⠠⡃⣿⡇⠀⠶⠀⠆⠰⠎⡷⢶⣾⣷⣿⠀⡆⣶⣶⢶⣿⠀⣚⢔⣶⠀⠀⣿⣶⣓⢰⣶⢰⣾⣳⡆⣾⣾⢰⠀⠀⢸⣾⠀⢰⢰⡇⡆⠀⣿
⠀⣂⠲⠂⠀⢒⡀⡂⠑⡃⠚⠒⠒⢶⠒⠀⠃⣓⢚⢐⠚⠠⠒⠐⠒⠀⠀⡒⢛⠒⢐⣒⠐⢓⠓⡂⡒⠚⣙⡀⠀⠸⠓⠀⠐⠐⠃⡊⠀⣺
⠀⣀⣰⡎⠀⣁⠀⡀⣁⡀⣁⣁⣀⣁⣉⡁⡁⣀⣀⣀⣁⠀⣀⢈⣀⠀⠀⣀⣀⣈⢀⣰⢀⣰⣀⡀⣐⣱⣉⡀⠀⢈⣁⠀⢀⢀⡀⡀⠀⣰
⠀⡎⣶⡇⠁⠀⠀⠁⠈⠅⡮⠭⢵⣷⠥⠀⡇⠤⢽⠨⣶⠀⢼⢸⢥⠀⠀⣽⡧⣼⠠⢽⠨⢽⡯⠅⢵⣷⠨⠁⠀⢩⢼⠀⠠⠨⡆⠅⠀⣾
⣈⠤⣿⡇⠀⣭⠀⡅⢨⡅⣭⣭⣭⣭⣭⠀⣅⣭⣭⣭⣽⠀⠴⡡⣭⣀⠀⣭⣭⠤⢨⣽⢨⣽⢮⣅⣽⣽⢬⠄⢀⢨⣽⡁⢨⢨⣍⡅⡁⣽
⠀⡇⣿⡇⠀⠀⠀⠀⠀⠀⡇⠀⢸⣿⣿⠀⡇⠀⢺⠐⣿⠀⣿⢸⢺⠀⠀⣿⡗⣿⠐⢺⠐⢺⡗⠃⢻⣿⠸⠀⠀⢸⢿⠀⢸⠸⡇⠇⠀⣿
⠀⢁⠿⡇⡀⠀⠀⡀⢀⡀⢇⣀⡨⡭⡉⠀⡅⠀⣸⢀⠽⠀⢹⢨⡉⠀⠀⣩⡏⢩⠈⣹⢈⣹⣏⡁⡹⡿⢈⣀⡀⣈⢹⠀⠈⢈⠇⡁⠀⢹
⠒⡀⣾⡇⠀⠒⠀⠂⠐⠂⡒⠒⢒⣒⣒⠀⡒⠒⢒⠒⣲⠀⣀⢂⢒⠀⠀⣒⣒⣀⢐⣺⢐⣺⣔⡒⣲⣲⢐⠀⠀⢐⣲⠂⢐⢐⡒⡂⠂⣺
⠀⡎⣶⡆⠀⠙⠀⠃⠘⠂⡟⠒⢻⣶⣶⠀⡇⠲⢷⠱⣶⠀⣶⢰⢷⠀⠀⣷⡶⣾⠸⢶⠸⢶⡶⠆⣾⣶⢰⠁⠀⢰⣶⠀⢱⢸⡇⡇⠈⣶
⠀⠊⣶⡆⠀⠉⠀⠁⠈⠀⠏⠀⠹⠶⠒⠀⠃⠀⠱⠁⠶⠀⠲⠰⠑⠀⠀⠳⠆⠚⠈⢰⠈⢰⡆⠀⢸⢶⠐⠁⠀⠐⢰⠀⠐⠈⠇⠁⠈⢲
⠀⠆⣶⡇⠀⠀⠀⠀⠑⠂⡾⠾⠾⠷⠶⠀⠆⠶⢶⠰⢶⠀⢶⠰⠶⠀⠀⠶⠶⠶⠰⢷⠰⢾⡶⠆⢶⣶⠰⠀⠀⠸⢾⠈⠸⠸⡆⠆⠀⢶
⠉⡔⣭⡇⠂⠉⠀⠃⠘⢃⡝⠛⢫⡯⣋⠀⠏⠉⠻⠙⣭⠀⢰⠱⠋⠈⣀⣿⠏⡰⠈⠻⠘⢻⡞⠋⢫⢯⠘⠂⠈⢸⢹⠁⠈⠘⡍⠃⠁⣽
⠤⠂⢿⡇⠀⠤⠀⠄⠠⠄⠧⠤⠴⠶⠤⠀⠦⠤⠼⠤⠾⠀⠘⠔⠤⠠⠀⠴⠦⠐⠠⠼⠠⢼⠣⠤⠼⠾⠠⠀⠀⠠⠼⠄⠠⠠⠦⠄⠄⢼
⠀⠤⣶⡆⠀⠤⠀⠄⠠⠄⡦⠤⢤⣦⠤⠀⠄⠤⢴⠤⢴⠀⢴⢰⠤⠀⠀⠤⡦⠤⠠⢴⠠⢴⡦⠄⢴⣶⠠⠄⠀⠠⢴⠀⠠⠠⡆⠄⠀⢼
⠀⠄⠿⠇⠀⠀⠀⠀⠀⠀⠅⠀⠨⠭⠠⠀⠄⠀⠨⠀⠭⠀⠬⠨⠠⠀⠀⠬⠅⠬⠀⠸⠀⠸⠅⠀⠸⠽⠀⠀⠀⠠⠸⠀⠀⠀⠅⠀⠀⠼
⠀⠀⣤⡅⠀⣀⠀⡀⢀⡀⣆⣀⣠⣤⣀⠀⡀⣀⣰⣀⣤⠀⠠⡠⣐⠀⠀⣀⣄⠀⢀⣠⢂⣨⢆⡀⣠⣤⢀⠀⠀⢀⣠⠀⢀⢀⡄⡀⠀⣨
⠀⡚⣀⡁⠑⠐⠢⠓⠈⠃⡌⣉⣁⣱⣁⠀⡅⣒⣙⢘⣀⠀⣌⢨⣁⠀⠀⣋⣕⣬⢐⣻⢈⣙⣉⡃⣃⣅⢚⠋⠀⢉⣈⠀⢀⢈⡀⡃⠀⣚
⠀⡋⣲⡂⠀⠨⠁⠉⠄⠁⡢⠀⣐⣚⣒⠠⡆⣉⣸⢨⣖⠀⣲⢐⣰⠀⠀⣓⣊⣖⢈⣙⢀⣘⣂⡁⣑⣒⢙⠁⠀⢐⣰⠀⢰⢠⡆⡇⠀⣻
⠀⡇⣿⡇⠀⠀⠀⠀⠀⠠⡇⠀⢸⣟⣿⠀⡃⠉⢙⠘⣿⠀⣻⢘⢛⠀⠠⣿⡛⣟⠘⢛⠘⢻⡟⠃⢻⣻⢘⠀⠀⢸⢻⠀⢘⢘⡇⡃⠀⣿
⠀⠆⣶⡆⠀⠀⠀⠀⠀⠀⡆⠀⢰⡶⠤⠀⠆⠀⢰⠀⢶⠀⢴⢰⠠⠀⠀⠶⡆⠴⠀⢰⠠⢼⡦⠄⢴⣶⠠⠀⠀⠠⢴⠀⠠⠠⡆⠄⠀⢾
⢀⠍⣿⡇⠀⣉⠀⡁⢈⡁⣏⣉⣩⣭⣭⠀⣅⣉⣹⣉⣽⠀⠽⡨⣩⠀⠀⣭⣍⠭⢈⣹⢈⣹⢏⣁⣹⣿⢈⠀⠀⢨⣹⡀⢈⢈⣅⡁⡀⣽
⠈⡖⣿⡇⠀⠛⠀⡃⢚⡃⣟⣛⣻⣿⣛⠀⡇⣛⣻⢛⣿⠀⣶⢱⣻⠀⠀⣿⣟⣶⢘⣻⢘⣻⣞⡃⣻⣿⢚⠂⠀⢸⣻⠁⢘⢘⡇⡃⠁⣿
⠠⡃⣿⡇⠀⠤⠀⠄⠠⠄⡧⠤⢼⣿⠿⠀⡇⠤⢼⠤⣿⠀⢛⢜⠼⠀⠀⣿⡧⣛⠰⢿⠸⢿⡻⠇⢿⣿⠸⠀⠀⢸⢿⠀⠸⠸⡇⠇⠄⣿
⠐⡀⣛⡃⠀⠒⠀⠂⠐⠂⡒⠒⢒⣒⣒⠀⡒⠒⢒⠒⣒⠄⣀⢂⢒⠀⠀⣖⡒⣀⠐⢚⠐⢚⣐⡂⣚⣚⢰⠀⠀⢐⣒⠂⢰⢐⡒⡂⠂⣚
```

### CODE REVIEW

**Comment by abuttari** [comment]
@amontoison my uneducated guess is:

the rp and cp arrays exist and are allocated in the Fortran code; the qr_mumps C interface takes a null C pointer and makes it point to the corresponding Fortran array. As far as I understand, in the Julia interface allocates an array and then expects qr_mumps to fill it up with the permutation. Could this explain the issue? Note that the same happens for the qrm_spfct_get_r routine: the R factor sparse matrix is allocated on the Fortran side of the code and a C pointer to its fields (irn, jcn and val) is returned through the C interface.

**Comment by abuttari** [comment]
I'd rather say `Ptr{Ptr{Cint}}`

**Comment by amontoison** [comment]
> I'd rather say `Ptr{Ptr{Cint}}`

It's not working for `qrm_spfct_get_rp` and `qrm_spfct_get_cp` :(
I can get the pointer of the `c_spmat` with `qrm_spfct_get_r` but after we can't work with it because I can't model the structure from the pointer.

**Comment by abuttari** [comment]
> > I'd rather say `Ptr{Ptr{Cint}}`
> 
> It's not working for `qrm_spfct_get_rp` and `qrm_spfct_get_cp` :( I can get the pointer of the `c_spmat` with `qrm_spfct_get_r` but after we can't work with it because I can't recover the structure from the pointer. It's not an array and I can't use `unsafe_wrap`.

how do you manage to pass Ptr{Ptr{Cint}}. I get an

```
ERROR: MethodError: no method matching unsafe_convert(::Type{Ptr{Int32}}, ::Int32)
```
error

**Comment by abuttari** [comment]
Let me explain how the code is supposed to work. The qrm code works pretty much like (assuming it's written in C):
```C
int qrm_spfct_get_r_c(qrm_spfct *spfct, int **rp){
*rp=spfct->rp;
}
```
so, it receives the address of a pointer object and makes the pointer point to an array which exists elsewhere. Therefore, on the Julia size there is no need to create a zero vector of size n. We just need to create a pointer object and pass its reference to qrm. Something like
```
            ptr=convert(Ptr{Cint},C_NULL)
            err = ccall(($fname, $lname), Cint, (Ref{c_spfct{$elty}}, Ptr{Ptr{Cint}}), spfct, Ref(ptr))
            (err ≠ 0) && throw(ErrorException(error_handling(err)))
            rp = unsafe_wrap(Array{Cint}, ptr, spfct.fct.m)
```
Actually this code does not work: it segfaults as soon as we try to read rp. This is because Ref(ptr) does not return the address of the ptr variable but returns 0. Any clue how to do this?

**Comment by amontoison** [comment]
@abuttari 
I think that we need this:
```julia
for (fname, lname, elty) in (("sqrm_spfct_get_rp_c", libsqrm, Float32   ),
                             ("dqrm_spfct_get_rp_c", libdqrm, Float64   ),
                             ("cqrm_spfct_get_rp_c", libcqrm, ComplexF32),
                             ("zqrm_spfct_get_rp_c", libzqrm, ComplexF64))
    @eval begin
        function qrm_spfct_get_rp(spfct :: qrm_spfct{$elty})
            ptr_rp = Ref{Ptr{Cint}}()
            err = ccall(($fname, $lname), Cint, (Ref{c_spfct{$elty}}, Ptr{Ptr{Cint}}), spfct, ptr_rp)
            (err ≠ 0) && throw(ErrorException(error_handling(err)))
            rp = unsafe_wrap(Array, ptr_rp[], spfct.fct.m)
            return rp
        end
    end
end

for (fname, lname, elty) in (("sqrm_spfct_get_cp_c", libsqrm, Float32   ),
                             ("dqrm_spfct_get_cp_c", libdqrm, Float64   ),
                             ("cqrm_spfct_get_cp_c", libcqrm, ComplexF32),
                             ("zqrm_spfct_get_cp_c", libzqrm, ComplexF64))
    @eval begin
        function qrm_spfct_get_cp(spfct :: qrm_spfct{$elty})
            ptr_cp = Ref{Ptr{Cint}}()
            err = ccall(($fname, $lname), Cint, (Ref{c_spfct{$elty}}, Ptr{Ptr{Cint}}), spfct, ptr_cp)
            (err ≠ 0) && throw(ErrorException(error_handling(err)))
            cp = unsafe_wrap(Array, ptr_cp[], spfct.fct.n)
            return cp
        end
    end
end
```
but I have the following errors:
```julia
julia> rp = qrm_spfct_get_rp(spfct)
ERROR: Unknown qr_mumps error: 40916048
Stacktrace:
 [1] qrm_spfct_get_rp(spfct::qrm_spfct{Float64})
   @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:9
 [2] top-level scope
   @ REPL[9]:1

julia> cp = qrm_spfct_get_cp(spfct)
ERROR: Unknown qr_mumps error: 49261968
Stacktrace:
 [1] qrm_spfct_get_cp(spfct::qrm_spfct{Float64})
   @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:24
 [2] top-level scope
   @ REPL[10]:1
```

**Comment by abuttari** [comment]
> @abuttari I think that we need this:
> 
> ```julia
> for (fname, lname, elty) in (("sqrm_spfct_get_rp_c", libsqrm, Float32   ),
>                              ("dqrm_spfct_get_rp_c", libdqrm, Float64   ),
>                              ("cqrm_spfct_get_rp_c", libcqrm, ComplexF32),
>                              ("zqrm_spfct_get_rp_c", libzqrm, ComplexF64))
>     @eval begin
>         function qrm_spfct_get_rp(spfct :: qrm_spfct{$elty})
>             ptr_rp = Ref{Ptr{Cint}}()
>             err = ccall(($fname, $lname), Cint, (Ref{c_spfct{$elty}}, Ptr{Ptr{Cint}}), spfct, ptr_rp)
>             (err ≠ 0) && throw(ErrorException(error_handling(err)))
>             rp = unsafe_wrap(Array, ptr_rp[], spfct.fct.m)
>             return rp
>         end
>     end
> end
> 
> for (fname, lname, elty) in (("sqrm_spfct_get_cp_c", libsqrm, Float32   ),
>                              ("dqrm_spfct_get_cp_c", libdqrm, Float64   ),
>                              ("cqrm_spfct_get_cp_c", libcqrm, ComplexF32),
>                              ("zqrm_spfct_get_cp_c", libzqrm, ComplexF64))
>     @eval begin
>         function qrm_spfct_get_cp(spfct :: qrm_spfct{$elty})
>             ptr_cp = Ref{Ptr{Cint}}()
>             err = ccall(($fname, $lname), Cint, (Ref{c_spfct{$elty}}, Ptr{Ptr{Cint}}), spfct, ptr_cp)
>             (err ≠ 0) && throw(ErrorException(error_handling(err)))
>             cp = unsafe_wrap(Array, ptr_cp[], spfct.fct.n)
>             return cp
>         end
>     end
> end
> ```
> 
> but I have the following errors:
> 
> ```julia
> julia> rp = qrm_spfct_get_rp(spfct)
> ERROR: Unknown qr_mumps error: 40916048
> Stacktrace:
>  [1] qrm_spfct_get_rp(spfct::qrm_spfct{Float64})
>    @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:9
>  [2] top-level scope
>    @ REPL[9]:1
> 
> julia> cp = qrm_spfct_get_cp(spfct)
> ERROR: Unknown qr_mumps error: 49261968
> Stacktrace:
>  [1] qrm_spfct_get_cp(spfct::qrm_spfct{Float64})
>    @ QRMumps ~/Bureau/git/QRMumps.jl/src/wrapper/qr_mumps_api.jl:24
>  [2] top-level scope
>    @ REPL[10]:1
> ```

This works like a charm. The problem was in qrm and is now fixed. It is possible to retrieve the R/U factor now. It seems that there is a problem for the non-symmetric case where r[rp,cp] is not upper triangular. Looking into this ASAP

**Comment by abuttari** [comment]
The behavior for rectangular matrix is actually correct: the resulting R factor is actually triangular but the rows of R are interleaved with empty rows. It can easily be permuted to upper-triangular form.

**Comment by amontoison** [comment]
> The behavior for rectangular matrix is actually correct: the resulting R factor is actually triangular but the rows of R are interleaved with empty rows. It can easily be permuted to upper-triangular form.

Thanks @abuttari! Do you plan to do a new release 0.3.5 soon or not?
I can just remove `(err ≠ 0) && throw(ErrorException(error_handling(err)))` if you don't plan to do a new release.

**Comment by abuttari** [comment]
> > The behavior for rectangular matrix is actually correct: the resulting R factor is actually triangular but the rows of R are interleaved with empty rows. It can easily be permuted to upper-triangular form.
> 
> Thanks @abuttari! Do you plan to do a new release 0.3.5 soon or not? I can just remove `(err ≠ 0) && throw(ErrorException(error_handling(err)))` if you don't plan to do a new release.

@amontoison actually I do not plan to make a new release so let's just remove the error check and keep this in mind when a new release will be ready

**Comment by amontoison** [comment]
Sorry for the delay @abuttari...
I'm back in France :fr:  for the holidays, I can finalize the PR.
I added the tests and updated the documentation.
If all tests passed with CI, I merge the PR and do a new release of QRMumps.jl.

**Pull request merged**
