### PR TITLE
Add mul! function

### PR DESCRIPTION
**Pull request by amontoison**
@abuttari 
It seems that `qrm_spmat_mv!` is not working.
Could you check it when you have time ?

### CODE REVIEW

**Comment by amontoison** [comment]
I found the culprit, it only works well when `beta=0`. It seems that you forget to take into account the value this parameter in the Fortran routine.

**Comment by amontoison** [comment]
I have a different issue if `transp='c'` with real matrices. The Fortran routine never finishes.

**Comment by abuttari** [comment]
> I found the culprit, it only works well when `beta=0`. It seems that you forget to take into account the value this parameter in the Fortran routine.

that's weird. in the qrm_spmat_mv routine there is this code:

`  if(beta .eq. qrm_zzero) then
     y = qrm_zzero
  else
     y = beta*y
  end if`

I'm not sure why this is not working. I need to look into this.

**Comment by abuttari** [comment]
> I also have a different issue if `transp='c'` with real matrices. The Fortran routine never finishes.

yep, I see where the problem is. I'll fix this ASAP

**Pull request closed without merging**
